server:
  port: 8080
spring:
  application:
    name: payments
  # Configurações do banco de dados H2
  datasource:
    url: jdbc:h2:file:./data/picpay
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      path: /h2-console
      enabled: true

  # Configuração para inicialização do SQL sempre
  sql:
    init:
      mode: always

  # Configurações do Kafka
  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      auto-offset-reset: earliest
      properties:
        spring:
          json:
            trusted:
              packages: "*"
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      topic: transaction-notification
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      #key-serializer: org.apache.kafka.common.serialization.StringSerializer
management:
  server:
    port: 9101
  endpoints:
    web:
      exposure:
        include: health, prometheus.yaml
      base-path: "/"
      path-mapping:
        prometheus: "metrics"
  metrics:
    tags:
      application: payments